/**
 * Task Manager Settings Controller
 * Handles configuration for Task Manager system
 */

import { Context } from 'hono'
import { Env, AuthUser } from '../types'

const DEFAULT_SETTINGS = {
  // General
  agentEnabled: true,
  agentInterval: 5,
  businessHoursOnly: false,
  businessHoursStart: '09:00',
  businessHoursEnd: '17:00',
  timezone: 'Australia/Sydney',

  // Task Numbering
  taskStartingNumber: 100,
  taskMinDigits: 3,

  // Deadline & Reminders
  defaultDeadline: 'none',
  customDeadlineHours: 24,
  reminder24h: true,
  reminder4h: true,
  reminder1h: false,
  reminder30m: false,
  reminderCustomEnabled: false,
  reminderCustomHours: 2,

  // Overdue Settings
  firstAlertMinutes: 60,
  repeatAlertHours: 4,

  // Escalation
  escalationEnabled: true,
  firstEscalationHours: 1,
  escalationIntervalHours: 4,
  maxEscalationLevel: 3,
  escalationBusinessHoursOnly: true,

  // Sub-Task Settings
  autoSyncNotes: true,
  notifyOnSubTaskCompletion: true,
  autoCloseParent: false,
  inheritParentDeadline: false,
  inheritParentPriority: true,
  inheritParentAssignee: false,

  // McCarthy AI
  aiEnabled: true,
  aiAutoGenerateDrafts: true,
  aiModel: 'llama-3.1',
  aiConfidenceThreshold: 70,
  aiRequireApproval: 'always',
  aiCanAddNotes: true,
  aiCanUpdateStatus: false,
  aiCanChangePriority: false,
  aiCanSendEmails: false,
  aiCanCloseTasks: false,
  aiCanCreateSubTasks: false,

  // SLA by Priority
  slaCritical: 4,
  slaHigh: 24,
  slaNormal: 72,
  slaLow: 168,
  slaCalculateFrom: 'creation',

  // Notifications
  notifyOnCreated: 'assignee',
  notifyOnAssigned: 'both',
  notifyOnStatusChanged: 'assignee',
  notifyOnPriorityChanged: 'both',
  notifyOnCompleted: 'both',
  notifyOnMention: 'mentioned',

  // Auto-Assignment
  autoAssignmentEnabled: true,
  autoAssignmentMethod: 'round-robin',
  maxTasksPerStaff: 10,
}

/**
 * GET /api/settings/task-manager
 * Get Task Manager settings
 */
export async function getTaskManagerSettings(c: Context<{ Bindings: Env }>) {
  try {
    const settingsJson = await c.env.APP_CONFIG?.get('task_manager_settings')
    const settings = settingsJson ? JSON.parse(settingsJson) : DEFAULT_SETTINGS

    return c.json({ settings })
  } catch (error) {
    console.error('[TaskManagerSettings] Get error:', error)
    return c.json({ error: 'Internal server error' }, 500)
  }
}

/**
 * PUT /api/settings/task-manager
 * Update Task Manager settings
 */
export async function updateTaskManagerSettings(c: Context<{ Bindings: Env }>) {
  try {
    const user = c.get('user') as AuthUser

    // Only admins can update settings
    if (user.role !== 'admin') {
      return c.json({ error: 'Forbidden' }, 403)
    }

    const body = await c.req.json()

    // Merge with defaults to ensure all fields exist
    const settings = { ...DEFAULT_SETTINGS, ...body }

    // Save to KV
    await c.env.APP_CONFIG?.put('task_manager_settings', JSON.stringify(settings))

    console.log(`[TaskManagerSettings] Settings updated by ${user.email}`)

    return c.json({ message: 'Settings updated successfully', settings })
  } catch (error) {
    console.error('[TaskManagerSettings] Update error:', error)
    return c.json({ error: 'Internal server error' }, 500)
  }
}

