import { useState, useEffect } from 'react'
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query'
import { api } from '../lib/api'
import { CheckIcon, ExclamationCircleIcon } from '@heroicons/react/24/outline'

export default function TaskManagerSettingsPage() {
  const queryClient = useQueryClient()
  const [successMessage, setSuccessMessage] = useState('')
  const [errorMessage, setErrorMessage] = useState('')

  // Fetch current settings
  const { data: settingsData, isLoading } = useQuery({
    queryKey: ['task-manager-settings'],
    queryFn: async () => {
      const response = await api.get('/api/settings/task-manager')
      return response.data.settings
    },
  })

  // Form state
  const [settings, setSettings] = useState({
    // General
    agentEnabled: true,
    agentInterval: 5,
    businessHoursOnly: false,
    businessHoursStart: '09:00',
    businessHoursEnd: '17:00',
    timezone: 'Australia/Sydney',

    // Task Numbering
    taskStartingNumber: 100,
    taskMinDigits: 3,

    // Deadline & Reminders
    defaultDeadline: 'none',
    customDeadlineHours: 24,
    reminder24h: true,
    reminder4h: true,
    reminder1h: false,
    reminder30m: false,
    reminderCustomEnabled: false,
    reminderCustomHours: 2,

    // Overdue Settings
    firstAlertMinutes: 60,
    repeatAlertHours: 4,

    // Escalation
    escalationEnabled: true,
    firstEscalationHours: 1,
    escalationIntervalHours: 4,
    maxEscalationLevel: 3,
    escalationBusinessHoursOnly: true,

    // Sub-Task Settings
    autoSyncNotes: true,
    notifyOnSubTaskCompletion: true,
    autoCloseParent: false,
    inheritParentDeadline: false,
    inheritParentPriority: true,
    inheritParentAssignee: false,

    // McCarthy AI
    aiEnabled: true,
    aiAutoGenerateDrafts: true,
    aiModel: 'llama-3.1',
    aiConfidenceThreshold: 70,
    aiRequireApproval: 'always',
    aiCanAddNotes: true,
    aiCanUpdateStatus: false,
    aiCanChangePriority: false,
    aiCanSendEmails: false,
    aiCanCloseTasks: false,
    aiCanCreateSubTasks: false,

    // SLA by Priority
    slaCritical: 4,
    slaHigh: 24,
    slaNormal: 72,
    slaLow: 168,
    slaCalculateFrom: 'creation',

    // Notifications
    notifyOnCreated: 'assignee',
    notifyOnAssigned: 'both',
    notifyOnStatusChanged: 'assignee',
    notifyOnPriorityChanged: 'both',
    notifyOnCompleted: 'both',
    notifyOnMention: 'mentioned',

    // Auto-Assignment
    autoAssignmentEnabled: true,
    autoAssignmentMethod: 'round-robin',
    maxTasksPerStaff: 10,
  })

  // Update form when settings load
  useEffect(() => {
    if (settingsData) {
      setSettings({ ...settings, ...settingsData })
    }
  }, [settingsData])

  // Save settings mutation
  const saveMutation = useMutation({
    mutationFn: async (data: typeof settings) => {
      return await api.put('/api/settings/task-manager', data)
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['task-manager-settings'] })
      setSuccessMessage('Settings saved successfully!')
      setErrorMessage('')
      setTimeout(() => setSuccessMessage(''), 3000)
    },
    onError: (error: any) => {
      setErrorMessage(error.response?.data?.error || 'Failed to save settings')
      setSuccessMessage('')
    },
  })

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault()
    saveMutation.mutate(settings)
  }

  if (isLoading) {
    return (
      <div className="min-h-screen bg-gray-50 p-6">
        <div className="max-w-4xl mx-auto">
          <div className="text-center py-12">Loading settings...</div>
        </div>
      </div>
    )
  }

  return (
    <div className="min-h-screen bg-gray-50 p-6">
      <div className="max-w-4xl mx-auto">
        {/* Header */}
        <div className="mb-6">
          <h1 className="text-2xl font-bold text-gray-900">Task Manager Settings</h1>
          <p className="text-sm text-gray-600 mt-1">Configure automation, reminders, escalation, and McCarthy AI</p>
        </div>

        {/* Success/Error Messages */}
        {successMessage && (
          <div className="mb-6 bg-green-50 border border-green-200 rounded-lg p-4 flex items-center gap-2">
            <CheckIcon className="w-5 h-5 text-green-600" />
            <span className="text-green-800">{successMessage}</span>
          </div>
        )}
        {errorMessage && (
          <div className="mb-6 bg-red-50 border border-red-200 rounded-lg p-4 flex items-center gap-2">
            <ExclamationCircleIcon className="w-5 h-5 text-red-600" />
            <span className="text-red-800">{errorMessage}</span>
          </div>
        )}

        <form onSubmit={handleSubmit}>
          {/* General Settings */}
          <div className="bg-white rounded-lg shadow mb-6">
            <div className="px-6 py-4 border-b border-gray-200">
              <h2 className="text-lg font-semibold text-gray-900">General Settings</h2>
            </div>
            <div className="p-6 space-y-4">
              <div className="flex items-center justify-between">
                <div>
                  <label className="text-sm font-medium text-gray-700">Enable Task Manager Agent</label>
                  <p className="text-xs text-gray-500">Automated monitoring and notifications</p>
                </div>
                <input
                  type="checkbox"
                  checked={settings.agentEnabled}
                  onChange={(e) => setSettings({ ...settings, agentEnabled: e.target.checked })}
                  className="h-4 w-4 text-indigo-600 rounded"
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Agent Run Interval</label>
                <select
                  value={settings.agentInterval}
                  onChange={(e) => setSettings({ ...settings, agentInterval: parseInt(e.target.value) })}
                  className="w-full border border-gray-300 rounded-lg px-3 py-2"
                >
                  <option value={5}>5 minutes</option>
                  <option value={15}>15 minutes</option>
                  <option value={30}>30 minutes</option>
                  <option value={60}>1 hour</option>
                </select>
              </div>

              <div className="flex items-center justify-between">
                <div>
                  <label className="text-sm font-medium text-gray-700">Business Hours Only</label>
                  <p className="text-xs text-gray-500">Only send notifications during business hours</p>
                </div>
                <input
                  type="checkbox"
                  checked={settings.businessHoursOnly}
                  onChange={(e) => setSettings({ ...settings, businessHoursOnly: e.target.checked })}
                  className="h-4 w-4 text-indigo-600 rounded"
                />
              </div>

              {settings.businessHoursOnly && (
                <div className="grid grid-cols-2 gap-4 ml-6">
                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-1">Start Time</label>
                    <input
                      type="time"
                      value={settings.businessHoursStart}
                      onChange={(e) => setSettings({ ...settings, businessHoursStart: e.target.value })}
                      className="w-full border border-gray-300 rounded-lg px-3 py-2"
                    />
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-1">End Time</label>
                    <input
                      type="time"
                      value={settings.businessHoursEnd}
                      onChange={(e) => setSettings({ ...settings, businessHoursEnd: e.target.value })}
                      className="w-full border border-gray-300 rounded-lg px-3 py-2"
                    />
                  </div>
                </div>
              )}
            </div>
          </div>

          {/* Task Numbering */}
          <div className="bg-white rounded-lg shadow mb-6">
            <div className="px-6 py-4 border-b border-gray-200">
              <h2 className="text-lg font-semibold text-gray-900">Task Numbering</h2>
            </div>
            <div className="p-6 space-y-4">
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Starting Number</label>
                <input
                  type="number"
                  value={settings.taskStartingNumber}
                  onChange={(e) => setSettings({ ...settings, taskStartingNumber: parseInt(e.target.value) })}
                  className="w-full border border-gray-300 rounded-lg px-3 py-2"
                  min={1}
                />
                <p className="text-xs text-gray-500 mt-1">Tasks will start from TSK-{settings.taskStartingNumber}</p>
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Minimum Digits</label>
                <input
                  type="number"
                  value={settings.taskMinDigits}
                  onChange={(e) => setSettings({ ...settings, taskMinDigits: parseInt(e.target.value) })}
                  className="w-full border border-gray-300 rounded-lg px-3 py-2"
                  min={1}
                  max={6}
                />
                <p className="text-xs text-gray-500 mt-1">Format: TSK-{String(settings.taskStartingNumber).padStart(settings.taskMinDigits, '0')}</p>
              </div>
            </div>
          </div>

          {/* Deadline & Reminders */}
          <div className="bg-white rounded-lg shadow mb-6">
            <div className="px-6 py-4 border-b border-gray-200">
              <h2 className="text-lg font-semibold text-gray-900">Deadline & Reminders</h2>
            </div>
            <div className="p-6 space-y-4">
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Default Task Deadline</label>
                <select
                  value={settings.defaultDeadline}
                  onChange={(e) => setSettings({ ...settings, defaultDeadline: e.target.value })}
                  className="w-full border border-gray-300 rounded-lg px-3 py-2"
                >
                  <option value="none">None</option>
                  <option value="24h">24 hours</option>
                  <option value="48h">48 hours</option>
                  <option value="1week">1 week</option>
                  <option value="custom">Custom</option>
                </select>
              </div>

              {settings.defaultDeadline === 'custom' && (
                <div className="ml-6">
                  <label className="block text-sm font-medium text-gray-700 mb-1">Custom Hours</label>
                  <input
                    type="number"
                    value={settings.customDeadlineHours}
                    onChange={(e) => setSettings({ ...settings, customDeadlineHours: parseInt(e.target.value) })}
                    className="w-full border border-gray-300 rounded-lg px-3 py-2"
                    min={1}
                  />
                </div>
              )}

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">Reminder Times</label>
                <div className="space-y-2">
                  <label className="flex items-center gap-2">
                    <input
                      type="checkbox"
                      checked={settings.reminder24h}
                      onChange={(e) => setSettings({ ...settings, reminder24h: e.target.checked })}
                      className="h-4 w-4 text-indigo-600 rounded"
                    />
                    <span className="text-sm text-gray-700">24 hours before deadline</span>
                  </label>
                  <label className="flex items-center gap-2">
                    <input
                      type="checkbox"
                      checked={settings.reminder4h}
                      onChange={(e) => setSettings({ ...settings, reminder4h: e.target.checked })}
                      className="h-4 w-4 text-indigo-600 rounded"
                    />
                    <span className="text-sm text-gray-700">4 hours before deadline</span>
                  </label>
                  <label className="flex items-center gap-2">
                    <input
                      type="checkbox"
                      checked={settings.reminder1h}
                      onChange={(e) => setSettings({ ...settings, reminder1h: e.target.checked })}
                      className="h-4 w-4 text-indigo-600 rounded"
                    />
                    <span className="text-sm text-gray-700">1 hour before deadline</span>
                  </label>
                  <label className="flex items-center gap-2">
                    <input
                      type="checkbox"
                      checked={settings.reminder30m}
                      onChange={(e) => setSettings({ ...settings, reminder30m: e.target.checked })}
                      className="h-4 w-4 text-indigo-600 rounded"
                    />
                    <span className="text-sm text-gray-700">30 minutes before deadline</span>
                  </label>
                </div>
              </div>
            </div>
          </div>

          {/* Overdue Task Settings */}
          <div className="bg-white rounded-lg shadow mb-6">
            <div className="px-6 py-4 border-b border-gray-200">
              <h2 className="text-lg font-semibold text-gray-900">Overdue Task Settings</h2>
            </div>
            <div className="p-6 space-y-4">
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">First Alert After (minutes)</label>
                <select
                  value={settings.firstAlertMinutes}
                  onChange={(e) => setSettings({ ...settings, firstAlertMinutes: parseInt(e.target.value) })}
                  className="w-full border border-gray-300 rounded-lg px-3 py-2"
                >
                  <option value={15}>15 minutes</option>
                  <option value={30}>30 minutes</option>
                  <option value={60}>1 hour</option>
                  <option value={120}>2 hours</option>
                </select>
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Repeat Alerts Every (hours)</label>
                <select
                  value={settings.repeatAlertHours}
                  onChange={(e) => setSettings({ ...settings, repeatAlertHours: parseInt(e.target.value) })}
                  className="w-full border border-gray-300 rounded-lg px-3 py-2"
                >
                  <option value={1}>1 hour</option>
                  <option value={2}>2 hours</option>
                  <option value={4}>4 hours</option>
                  <option value={8}>8 hours</option>
                </select>
              </div>
            </div>
          </div>

          {/* Escalation Settings */}
          <div className="bg-white rounded-lg shadow mb-6">
            <div className="px-6 py-4 border-b border-gray-200">
              <h2 className="text-lg font-semibold text-gray-900">Escalation Settings</h2>
            </div>
            <div className="p-6 space-y-4">
              <div className="flex items-center justify-between">
                <div>
                  <label className="text-sm font-medium text-gray-700">Enable Auto-Escalation</label>
                  <p className="text-xs text-gray-500">Automatically escalate overdue tasks</p>
                </div>
                <input
                  type="checkbox"
                  checked={settings.escalationEnabled}
                  onChange={(e) => setSettings({ ...settings, escalationEnabled: e.target.checked })}
                  className="h-4 w-4 text-indigo-600 rounded"
                />
              </div>

              {settings.escalationEnabled && (
                <>
                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-1">First Escalation Delay (hours)</label>
                    <select
                      value={settings.firstEscalationHours}
                      onChange={(e) => setSettings({ ...settings, firstEscalationHours: parseInt(e.target.value) })}
                      className="w-full border border-gray-300 rounded-lg px-3 py-2"
                    >
                      <option value={1}>1 hour</option>
                      <option value={2}>2 hours</option>
                      <option value={4}>4 hours</option>
                    </select>
                  </div>

                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-1">Escalation Interval (hours)</label>
                    <select
                      value={settings.escalationIntervalHours}
                      onChange={(e) => setSettings({ ...settings, escalationIntervalHours: parseInt(e.target.value) })}
                      className="w-full border border-gray-300 rounded-lg px-3 py-2"
                    >
                      <option value={2}>2 hours</option>
                      <option value={4}>4 hours</option>
                      <option value={8}>8 hours</option>
                      <option value={24}>24 hours</option>
                    </select>
                  </div>

                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-1">Max Escalation Level</label>
                    <select
                      value={settings.maxEscalationLevel}
                      onChange={(e) => setSettings({ ...settings, maxEscalationLevel: parseInt(e.target.value) })}
                      className="w-full border border-gray-300 rounded-lg px-3 py-2"
                    >
                      <option value={1}>1 (Team Leader only)</option>
                      <option value={2}>2 (Team Leader → Manager)</option>
                      <option value={3}>3 (Team Leader → Manager → Admin)</option>
                    </select>
                  </div>

                  <div className="flex items-center justify-between">
                    <div>
                      <label className="text-sm font-medium text-gray-700">Business Hours Only</label>
                      <p className="text-xs text-gray-500">Only escalate during business hours</p>
                    </div>
                    <input
                      type="checkbox"
                      checked={settings.escalationBusinessHoursOnly}
                      onChange={(e) => setSettings({ ...settings, escalationBusinessHoursOnly: e.target.checked })}
                      className="h-4 w-4 text-indigo-600 rounded"
                    />
                  </div>
                </>
              )}
            </div>
          </div>

          {/* Sub-Task Settings */}
          <div className="bg-white rounded-lg shadow mb-6">
            <div className="px-6 py-4 border-b border-gray-200">
              <h2 className="text-lg font-semibold text-gray-900">Sub-Task Settings</h2>
            </div>
            <div className="p-6 space-y-4">
              <div className="flex items-center justify-between">
                <div>
                  <label className="text-sm font-medium text-gray-700">Auto-Sync Notes</label>
                  <p className="text-xs text-gray-500">Sync notes between parent and child tasks</p>
                </div>
                <input
                  type="checkbox"
                  checked={settings.autoSyncNotes}
                  onChange={(e) => setSettings({ ...settings, autoSyncNotes: e.target.checked })}
                  className="h-4 w-4 text-indigo-600 rounded"
                />
              </div>

              <div className="flex items-center justify-between">
                <div>
                  <label className="text-sm font-medium text-gray-700">Notify on Sub-Task Completion</label>
                  <p className="text-xs text-gray-500">Notify parent task owner when sub-task is completed</p>
                </div>
                <input
                  type="checkbox"
                  checked={settings.notifyOnSubTaskCompletion}
                  onChange={(e) => setSettings({ ...settings, notifyOnSubTaskCompletion: e.target.checked })}
                  className="h-4 w-4 text-indigo-600 rounded"
                />
              </div>

              <div className="flex items-center justify-between">
                <div>
                  <label className="text-sm font-medium text-gray-700">Auto-Close Parent</label>
                  <p className="text-xs text-gray-500">Automatically close parent when all sub-tasks are completed</p>
                </div>
                <input
                  type="checkbox"
                  checked={settings.autoCloseParent}
                  onChange={(e) => setSettings({ ...settings, autoCloseParent: e.target.checked })}
                  className="h-4 w-4 text-indigo-600 rounded"
                />
              </div>

              <div className="flex items-center justify-between">
                <div>
                  <label className="text-sm font-medium text-gray-700">Inherit Parent Deadline</label>
                  <p className="text-xs text-gray-500">Sub-tasks inherit deadline from parent</p>
                </div>
                <input
                  type="checkbox"
                  checked={settings.inheritParentDeadline}
                  onChange={(e) => setSettings({ ...settings, inheritParentDeadline: e.target.checked })}
                  className="h-4 w-4 text-indigo-600 rounded"
                />
              </div>

              <div className="flex items-center justify-between">
                <div>
                  <label className="text-sm font-medium text-gray-700">Inherit Parent Priority</label>
                  <p className="text-xs text-gray-500">Sub-tasks inherit priority from parent</p>
                </div>
                <input
                  type="checkbox"
                  checked={settings.inheritParentPriority}
                  onChange={(e) => setSettings({ ...settings, inheritParentPriority: e.target.checked })}
                  className="h-4 w-4 text-indigo-600 rounded"
                />
              </div>

              <div className="flex items-center justify-between">
                <div>
                  <label className="text-sm font-medium text-gray-700">Inherit Parent Assignee</label>
                  <p className="text-xs text-gray-500">Sub-tasks inherit assignee from parent</p>
                </div>
                <input
                  type="checkbox"
                  checked={settings.inheritParentAssignee}
                  onChange={(e) => setSettings({ ...settings, inheritParentAssignee: e.target.checked })}
                  className="h-4 w-4 text-indigo-600 rounded"
                />
              </div>
            </div>
          </div>

          {/* McCarthy AI Settings */}
          <div className="bg-white rounded-lg shadow mb-6">
            <div className="px-6 py-4 border-b border-gray-200">
              <h2 className="text-lg font-semibold text-gray-900">McCarthy AI Settings</h2>
            </div>
            <div className="p-6 space-y-4">
              <div className="flex items-center justify-between">
                <div>
                  <label className="text-sm font-medium text-gray-700">Enable AI Task Execution</label>
                  <p className="text-xs text-gray-500">Allow McCarthy AI to assist with tasks</p>
                </div>
                <input
                  type="checkbox"
                  checked={settings.aiEnabled}
                  onChange={(e) => setSettings({ ...settings, aiEnabled: e.target.checked })}
                  className="h-4 w-4 text-indigo-600 rounded"
                />
              </div>

              {settings.aiEnabled && (
                <>
                  <div className="flex items-center justify-between">
                    <div>
                      <label className="text-sm font-medium text-gray-700">Auto-Generate Drafts</label>
                      <p className="text-xs text-gray-500">Automatically generate AI drafts for tasks</p>
                    </div>
                    <input
                      type="checkbox"
                      checked={settings.aiAutoGenerateDrafts}
                      onChange={(e) => setSettings({ ...settings, aiAutoGenerateDrafts: e.target.checked })}
                      className="h-4 w-4 text-indigo-600 rounded"
                    />
                  </div>

                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-1">AI Model</label>
                    <select
                      value={settings.aiModel}
                      onChange={(e) => setSettings({ ...settings, aiModel: e.target.value })}
                      className="w-full border border-gray-300 rounded-lg px-3 py-2"
                    >
                      <option value="llama-3.1">Llama 3.1 (Fast)</option>
                      <option value="gpt-4">GPT-4 (Advanced)</option>
                      <option value="claude-3">Claude 3 (Balanced)</option>
                    </select>
                  </div>

                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-1">
                      Confidence Threshold: {settings.aiConfidenceThreshold}%
                    </label>
                    <input
                      type="range"
                      min={0}
                      max={100}
                      value={settings.aiConfidenceThreshold}
                      onChange={(e) => setSettings({ ...settings, aiConfidenceThreshold: parseInt(e.target.value) })}
                      className="w-full"
                    />
                    <p className="text-xs text-gray-500">Minimum confidence for AI suggestions</p>
                  </div>

                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-1">Require Approval</label>
                    <select
                      value={settings.aiRequireApproval}
                      onChange={(e) => setSettings({ ...settings, aiRequireApproval: e.target.value })}
                      className="w-full border border-gray-300 rounded-lg px-3 py-2"
                    >
                      <option value="always">Always (Human-in-the-Loop)</option>
                      <option value="high-confidence">High Confidence Only</option>
                      <option value="never">Never (Fully Automated)</option>
                    </select>
                  </div>

                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-2">AI Can Execute</label>
                    <div className="space-y-2">
                      <label className="flex items-center gap-2">
                        <input
                          type="checkbox"
                          checked={settings.aiCanAddNotes}
                          onChange={(e) => setSettings({ ...settings, aiCanAddNotes: e.target.checked })}
                          className="h-4 w-4 text-indigo-600 rounded"
                        />
                        <span className="text-sm text-gray-700">Add internal notes</span>
                      </label>
                      <label className="flex items-center gap-2">
                        <input
                          type="checkbox"
                          checked={settings.aiCanUpdateStatus}
                          onChange={(e) => setSettings({ ...settings, aiCanUpdateStatus: e.target.checked })}
                          className="h-4 w-4 text-indigo-600 rounded"
                        />
                        <span className="text-sm text-gray-700">Update task status</span>
                      </label>
                      <label className="flex items-center gap-2">
                        <input
                          type="checkbox"
                          checked={settings.aiCanChangePriority}
                          onChange={(e) => setSettings({ ...settings, aiCanChangePriority: e.target.checked })}
                          className="h-4 w-4 text-indigo-600 rounded"
                        />
                        <span className="text-sm text-gray-700">Change priority</span>
                      </label>
                      <label className="flex items-center gap-2">
                        <input
                          type="checkbox"
                          checked={settings.aiCanSendEmails}
                          onChange={(e) => setSettings({ ...settings, aiCanSendEmails: e.target.checked })}
                          className="h-4 w-4 text-indigo-600 rounded"
                          disabled
                        />
                        <span className="text-sm text-gray-400">Send customer emails (always requires approval)</span>
                      </label>
                      <label className="flex items-center gap-2">
                        <input
                          type="checkbox"
                          checked={settings.aiCanCloseTasks}
                          onChange={(e) => setSettings({ ...settings, aiCanCloseTasks: e.target.checked })}
                          className="h-4 w-4 text-indigo-600 rounded"
                        />
                        <span className="text-sm text-gray-700">Close tasks</span>
                      </label>
                      <label className="flex items-center gap-2">
                        <input
                          type="checkbox"
                          checked={settings.aiCanCreateSubTasks}
                          onChange={(e) => setSettings({ ...settings, aiCanCreateSubTasks: e.target.checked })}
                          className="h-4 w-4 text-indigo-600 rounded"
                        />
                        <span className="text-sm text-gray-700">Create sub-tasks</span>
                      </label>
                    </div>
                  </div>
                </>
              )}
            </div>
          </div>

          {/* Save Button */}
          <div className="flex justify-end">
            <button
              type="submit"
              disabled={saveMutation.isPending}
              className="px-6 py-2 bg-indigo-600 text-white rounded-lg hover:bg-indigo-700 disabled:opacity-50"
            >
              {saveMutation.isPending ? 'Saving...' : 'Save Settings'}
            </button>
          </div>
        </form>
      </div>
    </div>
  )
}

